// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package foobarbaz

import (
	"context"
)

// Injectors from wire.go:

func initializeBaz(contextContext context.Context) (Baz, error) {
	foo := ProviderFoo()
	bar := ProviderBar(foo)
	baz, err := ProviderBaz(contextContext, bar)
	if err != nil {
		return Baz{}, err
	}
	return baz, nil
}
